CREATE TABLE "ORDERS" (
	"ORDERID"	NUMBER(2)		NOT NULL,
	"SALEPRICE"	NUMBER(8)		NULL,
	"ORDERDATE"	DATE		NULL,
	"CUSTID"	NUMBER(2)		NOT NULL,
	"BOOKID"	NUMBER(2)		NOT NULL
);

CREATE TABLE "CUSTOMER" (
	"CUSTID"	NUMBER(2)		NOT NULL,
	"NAME"	VARCHAR2(40)		NULL,
	"ADDRESS"	VARCHAR2(50)		NULL,
	"PHONE"	VARCHAR2(20)		NULL
);

CREATE TABLE "BOOK" (
	"BOOKID"	NUMBER(2)		NOT NULL,
	"BOOKNAME"	VARCHAR2(40)		NULL,
	"PUBLISHER"	VARCHAR2(40)		NULL,
	"PRICE"	NUMBER(8)		NULL
);

