CREATE TABLE "SCOTT.EMP" (
	"EMPNO"	NUMBER(4)		NOT NULL,
	"ENAME"	VARCHAR2(10)		NULL,
	"JOB"	VARCHAR2(9)		NULL,
	"MGR"	NUMBER(4)		NULL,
	"SAL"	NUMBER(7,2)		NULL,
	"COMM"	NUMBER(7,2)		NULL,
	"DEPTNO"	NUMBER(2)		NULL,
	"DEPTNO2"	NUMBER(2)		NOT NULL,
	"DNAME"	VARCHAR2(14)		NOT NULL
);

CREATE TABLE "SCOTT.DEPT" (
	"DEPTNO"	NUMBER(2)		NOT NULL,
	"DNAME"	VARCHAR2(14)		NOT NULL,
	"LOC"	VARCHAR2(13)		NULL
);

