DML: SELECT, INSERT, UPDATE, DELETE
DDL: CREATE TABLE, ALTER TABLE, DROP TABLE
DCL: GRANT(권한을 승인해주는 것), REVOKE(빼는것?)
TCL: COMMIT(승인), ROLLBACK(다시 되돌리는것)


DESC EMP;
DESC dept;


SELECT EMPNO, DEPTNO
FROM EMP;

SELECT DISTINCT DEPTNO
FROM EMP;

SELECT ALL DEPTNO
FROM EMP;

--별칭주기(SAL*12를 ANNUAL로)
SELECT ENAME, SAL, SAL*12 AS ANNUAL
FROM EMP
ORDER BY SAL DESC, ANNUAL ASC;


--오름차순, 내림차순
SELECT ENAME, SAL, DEPTNO, SAL*12 AS ANNUAL
FROM EMP
ORDER BY SAL DESC, ANNUAL ASC;

SELECT *
FROM EMP
ORDER BY DEPTNO ASC, SAL DESC;

SELECT DEPTNO, SAL
FROM EMP
ORDER BY DEPTNO ASC, SAL DESC;

--부서번호가 30인 데이터
SELECT *
FROM EMP
WHERE DEPTNO = 30;
--7782사원 정보
SELECT *
FROM EMP
WHERE EMPNO=7782;

SELECT *
FROM EMP
WHERE DEPTNO=30
AND JOB ='SALESMAN';

SELECT *
FROM EMP
WHERE DEPTNO = 30
OR JOB = 'CLERK';

SELECT * 
FROM EMP
WHERE SAL >=2500
    AND JOB ='ANALYST';

--NOT EQUQL
SELECT * 
FROM EMP
WHERE DEPTNO <> 10;

--IN연산자
SELECT *
FROM EMP
WHERE JOB= 'MANAGER'
    OR JOB= 'SALESMAN'
    OR JOB= 'CLERL';

--이름의 두번째 글자가 A인 사원
SELECT ENAME
FROM EMP
WHERE ENAME LIKE '_A%';

-COMM 값이 비어있는 사람들
SELECT * 
FROM EMP
WHERE COMM =NULL;

SELECT *
FROM EMP
WHERE COMM IS NULL;

--P142
--7788:SCOTT
SELECT CONCAT(EMPNO, ENAME),
CONCAT(EMPNO, CONCAT(':', ENAME))
FROM EMP
WHERE ENAME ='SCOTT';

--15를 4로 나눈 나머지
SELECT MOD(15, 4)
FROM DUAL;

--날짜 함수
--지금 시스템 데이트는?
SELECT SYSDATE 
FROM DUAL;

--ADD_MONTHS()

--9
SELECT SAL, TO_CHAR(SAL, '$999,999') AS SAL_$
FROM EMP;

--NULL값 처리 NVL
SELECT *
FROM EMP
WHERE COMM IS NULL;
--NULL인 COMM을 0으로 바꾸어서 출력
SELECT EMPNO, ENAME, JOB, COMM
FROM EMP
WHERE COMM IS NULL;

SELECT EMPNO, ENAME, JOB, NVL(COMM,0)
FROM EMP
WHERE COMM IS NULL;

--NVL2
SELECT EMPNO, ENAME, JOB, NVL(COMM,0), 
NVL2(COMM,'O','X') AS NVL2
FROM EMP;


